[package]
name = "wasm-fractals"
version = "0.1.0"
authors = ["Corentin Junod <corentin.junod@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
num = "0.4.0"
num-bigint = "0.4.3"
num-bigfloat = "1.4.1"

